"""
LinkedIn Bot Configuration Data
Edit these lists for your LinkedIn bot behavior
"""

# Keywords to search for on LinkedIn
# Posts containing these keywords will be found and potentially liked
KEYWORDS = [
    "Eerste bestelling binnen",
    "Onze webshop is live",
    "Nieuwe producten online",
    "We gaan starten met verzenden",
    "Verzending geregeld",
    "Webshop tips",
    "Zelf pakketten versturen",
    "Kleine ondernemer",
    "Handgemaakte producten",
    "Verzending vanuit huis",
    "Drukte in ons magazijn",
    "Orderverwerking optimaliseren",
    "Voorraadbeheer verbeteren",
    "Inpakken en verzenden",
    "Nieuwe fulfilment partner",
    "Logistiek uitbesteden",
    "Meer bestellingen dan verwacht",
    "Orders verwerken",
    "Productiviteit magazijn",
    "Verkopen via Etsy",
    "Bol.com verkoper",
    "Eigen merk gestart",
    "Wix webshop",
    "Shopify store",
    "WooCommerce webshop",
    "Marktplaats verkopen",
    "Verzendlabels printen",
    "Orderpicken makkelijker maken",
    "Magazijnapp gezocht",
    "QR scannen producten",
    "Realtime voorraad",
    "Voorraad bijhouden webshop",
    "Pick & pack software",
    "Magazijnoptimalisatie",
    "Logistiek management software",
    "Orderpick automatisering",
    "Efficiënte logistiek",
    "Digitale magazijnoplossing",
    "Warehouse performance",
    "Magazijn KPI's",
    "Slimme logistiek",
    "Digitalisering magazijn",
    "Logistiek inzicht",
    "Logistieke operatie",
    "Logistiek team aansturen",
    "Magazijn coördinator",
    "Route optimalisatie",
    "Webshop automatisering",
    "E-commerce groei",
    "Webshop efficiëntie",
    "E-commerce tools",
    "Verzendstrategie",
    "Webwinkel software",
    "Fulfilment automatisering",
    "E-commerce optimalisatie",
    "Webshop logistieke oplossing",
    "Orderverwerkingsproces",
    "Webshop verzendoplossing",
    "Product handling",
    "Verzendplatform",
    "Pick & ship",
    "Webshop verbeteren",
    "Logistiek directeur",
    "Operations manager",
    "E-commerce manager",
    "Fulfilment manager",
    "Supply chain specialist",
    "Head of operations",
    "Logistiek coördinator",
    "Online retailer",
    "Webshop starter",
    "Retail logistiek",
    "B2C verzending",
    "B2B e-commerce",
    "Direct-to-consumer",
    "E-logistics specialist",
    "Smart warehousing",
    "AI in logistiek",
    "IoT logistiek",
    "Predictive logistics",
    "Automatisering MKB",
    "Innovatie in magazijnen",
    "Logistieke schaalbaarheid",
    "Logistiek 4.0",
    "Slimme softwareoplossingen",
    "Digitale transformatie logistiek",
    "ERP koppeling",
    "EDI integratie",
    "Picklijsten genereren",
    "Automatische orderverwerking",
    "Realtime tracking",
    "QR scan app",
    "API koppelingen",
    "Backoffice integratie",
    "WMS koppeling",
    "Multi-warehouse beheer",
    "Orderpicken",
    "Logistiek",
    "WMS",
    "Voorraadbeheer",
    "Magazijnbeheer",
    "Picklijsten",
    "Warehouse Management",
    "Logistiek manager",
    "E-fulfilment",
    "E-commerce logistiek",
    "Logistieke optimalisatie",
    "Distributiecentrum",
    "Voorraadoptimalisatie",
    "Dagstart magazijn",
    "Pick to Light",
    "Efficiënt orderpicken",
    "Barcode scanning",
    "Orderverwerking",
    "Logistieke software",
    "Snelle leveringen",
    "Same day delivery",
    "Magazijnautomatisering",
    "Verzendproces optimalisatie",
    "Logistieke innovatie",
    "Retourlogistiek",
    "Warehouse robotica",
    "Picking proces",
    "Scannen met QR",
    "Digitaal orderpicken",
    "Orderpick systeem",
    "Magazijnmedewerker",
    "Mobiel scannen",
    "QR picking",
    "Slim voorraadbeheer",
    "Realtime voorraad",
    "Logistiek proces",
    "Productiviteit magazijn",
    "Orderpick efficiency",
    "Paperless picking",
    "Pick by Scan",
    "Magazijn digitaliseren",
    "Logistiek dashboard",
    "Voorraadnauwkeurigheid",
    "Logistieke trends",
    "Magazijn apps",
    "Pick performance",
    "Mobiele orderpicking",
    "Kleine webshop",
    "Webshop logistiek",
    "Zelf verzenden",
    "Zelf pakketten versturen",
    "Verzendsoftware",
    "Klein magazijn",
    "Startende webshop",
    "Kleine ondernemers",
    "MKB logistiek",
    "Eenvoudig orderpicken",
    "Verzendlabels maken",
    "Sneller verzenden",
    "Verzending automatiseren",
    "Webshop voorraad",
    "Schaalbare logistiek",
    "Kostenefficiënt verzenden",
    "Webshop gestart",
    "Pakketten verzenden",
    "Fulfilment",
    "Magazijn",
    "Webshop groeit",
    "E-commerce",
    "Verzenden vanuit huis",
    "Nieuwe opslagruimte",
    "Verzendproces",
    "Logistieke uitdaging",
    "Drukte in magazijn",
    "Productiviteit verhogen",
    "Efficiëntie in magazijn",
    "Klaar voor verzenden",
    "Nieuwe klanten",
    "Bestellingen verwerken",
    "Voorraad bijhouden",
    "Webshop eigenaar",
    "MKB ondernemer",
    "Inpakken en verzenden",
    "Magazijnsoftware",
    "Voorraad op orde",
    "Retouren verwerken",
    "Logistieke partner gezocht",
    "Fulfilment partner gezocht",
    "Verzendlabels printen",
    "Pick & pack",
    "Groeiende webshop",
    "Orderverwerking verbeteren",
    "Warehouse efficiency",
    "Inbound logistiek",
    "Outbound logistiek",
    "Order fulfilment",
    "Third party logistics",
    "3PL partner",
    "Last mile logistiek",
    "Verzendkosten besparen",
    "Shopify",
    "WooCommerce",
    "Shopify apps",
    "Shopify logistiek",
    "WooCommerce verzenden",
    "Magento",
    "Wix webwinkel",
    "Bol.com logistiek",
    "Verzend integraties",
    "Webwinkel automatisering",
    "Plug&play fulfilment",
    "Shopify voorraadbeheer",
    "Webshop koppeling",
    "API integratie webshop",
    "E-commerce platform",
    "Etsy verkoper",
    "Marktplaats verkopen",
    "Multi-channel verkoop",
    "Bol verkoper platform",
    "Shopify fulfilment",
    "Automatisch verzenden",
    "E-commerce integraties",
    "PostNL integratie",
    "DHL verzenden",
    "Sendcloud",
    "MyParcel",
    "EasyParcel",
    "Shipping software",
    "Webshop plugins",
]

# Words to exclude - posts containing these will be skipped
# Even if they match keywords
EXCLUDEWORDS = [
    "vacature",
    "werken bij",
    "stage",
    "solliciteer",
    "hiring",
    "#hiring",
    "#opentowork",
    "opentowork",
    "job offer",
    "student",
    "job alert",
    "internship",
    "werkstudent",
    "verhuisbericht",
    "overlijden",
    "rip",
    "condoleance",
    "rouw",
    "trouwfeest",
    "bruiloft",
    "verloving",
    "geboorte",
    "baby geboren",
    "corona",
    "covid",
    "pandemie",
    "trump",
    "politiek",
    "verkiezingen",
    "kabinet",
    "minister",
    "pvda",
    "vvd",
    "groenlinks",
    "forum voor democratie",
    "fvd",
    "geert wilders",
    "baudet",
    "thierry wilders",
    "rutte",
    "biden",
    "putin",
    "poetin",
    "oorlog",
    "gaza",
    "israël",
    "palestina",
    "hamas",
    "ukraine",
    "oekraïne",
    "rusland",
    "seks",
    "sex",
    "porno",
    "porna",
    "erotiek",
    "nudes",
    "naakt",
    "onlyfans",
    "billie eilish feet",
    "bdsm",
    "misbruik",
    "verkrachting",
    "pedo",
    "kindermisbruik",
    "aanranding",
    "misdrijf",
    "zedenmisdrijf",
]

# LinkedIn profiles of interesting people
# The bot will visit their activity pages and like recent posts
INTERESTING_PEOPLE = [
    # Add more LinkedIn profile URLs here
    # Format: https://www.linkedin.com/in/username/
]